spring:
  application:
    name: demowhatsapp
  jpa:
    hibernate:
      ddl-auto: update
    database: POSTGRESQL
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
  datasource:
    initialization-mode: always
    platform: postgresql
    url: jdbc:postgresql://localhost:5432/demowhatsappdb
    username: postgres
    password: postgres
  kafka:
    bootstrap-servers: localhost:9092
server:
  port: 8080
  servlet:
    context-path: /api